version: '3'
services:
  # docker run lightninglabs/lnd:v0.15.1-beta --bitcoin.active --bitcoin.mainnet --bitcoin.node=neutrino
  lnd:
    image: lightninglabs/lnd:v0.15.1-beta
    container_name: lnd
    restart: always
    command:
      - --bitcoin.active
      - --bitcoin.mainnet
      - --bitcoin.node=neutrino
  rtl:
    image: shahanafarooqui/rtl:0.13.1
    container_name: rtl
    restart: always
  thunderhub:
    image: apotdevin/thunderhub:v0.13.16
    container_name: thunderhub
    restart: always